### ISSUE TITLE
api path kinda like isssue

### ISSUE THREAD

**Issue by sridhar885** [spencerwooo/onedrive-vercel-index#773]
[GET] /api/?path=/
22:50:30:78
2022-10-11T17:20:32.164Z	b29a4095-2bda-441d-ab2e-46b4fe833090	ERROR	[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled
    at parseError (/var/task/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/var/task/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14)
2022-10-11T17:20:32.322Z	b29a4095-2bda-441d-ab2e-46b4fe833090	ERROR	[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled
    at parseError (/var/task/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/var/task/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14)
2022-10-11T17:20:33.013Z	b29a4095-2bda-441d-ab2e-46b4fe833090	ERROR	[ioredis] Unhandled error event: ReplyError: WRONGPASS invalid username-password pair or user is disabled
    at parseError (/var/task/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/var/task/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14)
2022-10-11T17:20:33.016Z	b29a4095-2bda-441d-ab2e-46b4fe833090	ERROR	ReplyError: WRONGPASS invalid username-password pair or user is disabled
    at parseError (/var/task/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/var/task/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'auth', args: [ '8fa4be314355402698405177c55420fd', '' ] }
}
2022-10-11T17:20:33.016Z	b29a4095-2bda-441d-ab2e-46b4fe833090	ERROR	ReplyError: WRONGPASS invalid username-password pair or user is disabled
    at parseError (/var/task/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:179:12)
    at parseType (/var/task/node_modules/.pnpm/redis-parser@3.0.0/node_modules/redis-parser/lib/parser.js:302:14) {
  command: { name: 'auth', args: [ '8fa4be314355402698405177c55420fd', '' ] }
}
RequestId: b29a4095-2bda-441d-ab2e-46b4fe833090 Error: Runtime exited with error: exit status 1
Runtime.ExitError

i have  aE5 subscription sir i have given everything correct 
for redis i given only redis url sir 
why is this error occurs 
i appreciate for creating this kinda llike a cool web Nice!!!!!!!

**Comment by spencerwooo** [comment]
> ERROR ReplyError: WRONGPASS invalid username-password pair or user is disabled

Your `REDIS_URL` is wrong.

**Comment by sridhar885** [comment]
> > ERROR ReplyError: WRONGPASS invalid username-password pair or user is disabled
> 
> Your `REDIS_URL` is wrong.

Sir can i contact you in telegram
